import { StyleSheet } from "react-native";

export const COLORS = {
  text: "#EAEAEA",
  subText: "#BDBDBD",
  card: "rgba(30, 30, 32, 0.85)",
  border: "rgba(255, 255, 255, 0.1)",
  background: "#0A0A1A",
  awake: "#FFB86B",
  rem: "#D7BFFF",
  light: "#A5C9FF",
  deep: "#5A9DFF",
};

export const styles = StyleSheet.create({
  scrollContent: { paddingHorizontal: 16, paddingBottom: 100 },
  headerContainer: { paddingVertical: 12 },
  headerTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 8,
    marginBottom: 20,
  },
  headerTitle: { color: COLORS.text, fontSize: 32, fontWeight: "bold" },
  headerMidRow: {
    flexDirection: "row",
    backgroundColor: "rgba(128,128,128,0.2)",
    borderRadius: 20,
    alignSelf: "center",
    marginBottom: 20,
  },
  periodButton: {
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 20,
  },
  activePeriodButton: { backgroundColor: "rgba(255,255,255,0.9)" },
  periodText: { color: COLORS.subText, fontSize: 16, fontWeight: "bold" },
  activePeriodText: { color: "black" },
  headerBottomRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 8,
    marginBottom: 16,
  },
  dateText: { color: COLORS.text, fontSize: 18, fontWeight: "600" },

  // --- 일일 뷰 스타일 ---
  scoreCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 20,
    marginBottom: 24,
  },
  scoreSubtitle: { color: COLORS.subText, fontSize: 16, marginBottom: 4 },
  scoreValue: { color: COLORS.text, fontSize: 48, fontWeight: "bold" },
  scoreLabel: { fontSize: 18, fontWeight: "normal", color: COLORS.subText },
  starContainer: { flexDirection: "row", gap: 6, marginVertical: 12 },
  insightText: { color: COLORS.subText, fontSize: 15, lineHeight: 22 },
  primaryMetricsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 16,
  },
  primaryCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 20,
    flex: 1,
    position: "relative",
  },
  primaryLabel: { color: COLORS.subText, fontSize: 15, marginBottom: 8 },
  primaryValue: { color: COLORS.text, fontSize: 24, fontWeight: "bold" },
  primaryUnit: { fontSize: 16, color: COLORS.subText },
  qualityBadge: {
    position: "absolute",
    bottom: 12,
    right: 12,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  badgeText: { color: "white", fontSize: 12, fontWeight: "bold" },
  legendDisclaimer: {
    color: COLORS.subText,
    fontSize: 12,
    lineHeight: 18,
    textAlign: "center",
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  hypnogramContainer: {
    marginTop: 20,
    height: 120,
    justifyContent: "flex-end",
  },
  hypnogramChart: { flexDirection: "row", alignItems: "flex-end", height: 100 },
  hypnoBar: { width: 3, marginHorizontal: 0.5, borderRadius: 2 },
  timeLabelContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    paddingHorizontal: 4,
  },
  timeLabel: { color: COLORS.subText, fontSize: 12 },
  stageRow: { flexDirection: "row", alignItems: "center", marginTop: 16 },
  stageLabel: { color: COLORS.subText, fontSize: 15, width: "25%" },
  barContainer: { flex: 1, height: 24, justifyContent: "center" },
  idealRange: {
    backgroundColor: "rgba(128,128,128,0.2)",
    height: "100%",
    position: "absolute",
    borderRadius: 4,
  },
  actualBar: { height: 8, borderRadius: 4 },

  // --- 주간/월간 뷰 공통 스타일 ---
  mainValueLg: {
    color: COLORS.text,
    fontSize: 48,
    fontWeight: "bold",
    textAlign: "center",
  },
  mainUnitLg: { fontSize: 32, fontWeight: "normal" },
  subText: {
    color: COLORS.subText,
    fontSize: 16,
    textAlign: "center",
    marginBottom: 20,
  },

  // --- 주간 뷰 스타일 ---
  weeklyChartContainer: {
    flexDirection: "row",
    height: 180,
    alignItems: "flex-end",
    justifyContent: "space-around",
    paddingHorizontal: 10,
  },
  weeklyBarWrapper: { flex: 1, alignItems: "center", gap: 8 },
  stackedBar: {
    width: 30,
    justifyContent: "flex-end",
    borderRadius: 6,
    overflow: "hidden",
  },
  dayLabel: { color: COLORS.subText, fontSize: 14 },

  // --- 공통 카드 및 섹션 스타일 ---
  card: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
  },
  metricRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    marginTop: 14,
  },
  metricLabel: { color: COLORS.subText, fontSize: 15 },
  metricValue: { color: COLORS.text, fontSize: 16, fontWeight: "600" },
  metricValueSm: {
    color: COLORS.text,
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 4,
  },
  duoContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 8,
  },
  duoItem: { alignItems: "center" },
  legendContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingTop: 16,
    marginTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  legendItem: { flexDirection: "row", alignItems: "center" },
  legendDot: { width: 8, height: 8, borderRadius: 4, marginRight: 6 },
  legendText: { color: COLORS.subText, fontSize: 12 },
});
